use_frameworks!

platform :ios, '10.0'

target 'DSignerClientsTest_Example' do
  pod 'DSignerClientsTest', :path => '../'

  target 'DSignerClientsTest_Tests' do
    inherit! :search_paths

    
  end
end
